[project]
name = "modalg"
version = "0.1.0"
description = "Library for modern algebraic computations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "pandas>=2.0.0",
  "numpy>=1.24.0",
  "ipython>=8.0.0",
  "visidata>=0.9.0",
]
