## SymmetricGroups 


# Note that in Sage, permutations are applied from left to right.
G = SymmetricGroup (5)
sigma = G ( " (1 ,3) (2 ,5 ,4) " )
sigma * sigma

S = SymmetricGroup(5)
A = G('(1,2)(4,5)')
B = G('(1,5,3)(2,4)')
# Apply B first if you want to do A* B. Start from right to left.
B * A

# Function to do right to left composition
def rl(a, b):
    # Do right to left composition
    return b * a  # reverse order

# pg 150 ex 1
S3 = SymmetricGroup(3)
S12 = S3((1, 2))
S13 = S3((1, 3))
S23 = S3((2, 3))
S12 * S13
S123 = S3((1, 2, 3))
rl(S12, S13)

# (23)H = (123)H
rl(S123, S13)
rl(S23, S13)



# Dihedral groups

G = DihedralGroup(4)
G




# My library
import sys
sys.path.insert(0, '/home/alain/Documents/ModAlg/src')

from modalg.groups import U, Z
from modalg.groups import Cartesian, CartesianMatrix

U(10).cyclic(3)
U(10).generators()

print(U(49).group())

# Subgroup of Z_9 generated by 3:
Cartesian([0, 3, 6]).matrix(lambda a, b: (a + b) % 9).to_df()
Cartesian([1, 3]).matrix(lambda a, b: (a + b) % 9).to_df()

# https://www.youtube.com/@babymurcielaga9 

Z9 = Z(9)
Z9.generators()
